const List<String> occupations = [
  'Accountant',
  'Architect',
  'Artist',
  'Business Owner',
  'Civil Servant',
  'Consultant',
  'Customer Service',
  'Driver',
  'Engineer',
  'Farmer',
  'Healthcare Worker',
  'Lawyer',
  'Manager',
  'Medical Doctor',
  'Nurse',
  'Salesperson',
  'Self-Employed',
  'Student',
  'Teacher',
  'Technician',
  'Tradesperson',
  'Unemployed',
  'Other',
];
